name: CI/CD Deploy Backend to Azure Container Apps

on:
  push:
  # Only on master branch
    branches:
      - master

env:
  # your Azure resources
  ACR_NAME: acrcoworkingprod
  ACR_LOGIN_SERVER: acrcoworkingprod.azurecr.io
  RESOURCE_GROUP: rg-coworking-prod
  CONTAINERAPP_NAME: app-coworking-api

jobs:
  ## ─── 1) build & push ──────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-output.outputs.image }}
    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name:  Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name:  Build & Push image
        id: build-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./RadencyBack/RadencyBack/Dockerfile
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/coworking-svc:${{ github.sha }}
        # expose the fully-qualified image ref as a job output
      - name:  Set output
        id: set-output
        run: echo "image=${{ACR_LOGIN_SERVER}}/coworking-svc:${GITHUB_SHA}" >> $GITHUB_OUTPUT
        env:
          ACR_LOGIN_SERVER: ${{ env.ACR_LOGIN_SERVER }}
          GITHUB_SHA: ${{ github.sha }}

  ## ─── 2) deploy ────────────────────────────────────────────────────────────────
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name:  Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name:  Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name ${{ env.CONTAINERAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ needs.build.outputs.image }} \
            --environment-variables \
                ASPNETCORE_ENVIRONMENT=Production \
                DefaultConnection="${{ secrets.DATABASE_CONNECTION_STRING }}"
